runmode: release
server:
  addr: :11400
registry:
  registry_name: kuko
  register_address: 127.0.0.1
  health_check_port: 11400
log:
  logger_file: ./logs/kuko.log
  log_max_date: 7
  log_rotate_date: 1
biz_log:
  logger_file: ./logs/biz_kuko.log
  log_max_date: 7
  log_rotate_date: 1
db:
  name: kuko
  location: 127.0.0.1
  port: 3306
  username: root
  passwd: 123456